version: '3'
services:

  django_backend:
    image: cbers_cc_backend_django
    container_name: cbers_cc_backend_django
    build:
      context: .
      dockerfile: ./infra/compose/django/Dockerfile
    command: /home/cbers_cc/start
    env_file:
      - .env
    volumes:
      - ./src/cbers_cc:/home/cbers_cc/src/cbers_cc
    ports:
      - '80:8000'

  redis:
    image: redis:alpine
    container_name: cbers_cc_backend_redis

  celery:
    image: cbers_cc_backend_celery
    container_name: cbers_cc_backend_celery
    restart: always
    build:
      context: .
      dockerfile: ./infra/compose/django/Dockerfile
    command: /home/cbers_cc/start-celeryworker
    volumes:
      - ./src/cbers_cc:/home/cbers_cc/src/cbers_cc
    env_file:
      - .env
    depends_on:
      - django_backend
      - redis