# Generated by Django 4.2.1 on 2023-05-28 19:03

from django.db import migrations


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA cbers_cc_plugin')
    ]

