# Generated by Django 4.2.1 on 2023-05-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbers_cc_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'cbers_cc_plugin"."embedding',
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdf', models.JSONField(null=True)),
                ('metadata', models.JSONField(null=True)),
                ('embbeding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbers_cc_plugin.embedding')),
            ],
            options={
                'db_table': 'cbers_cc_plugin"."reference_image',
            },
        ),
    ]
