# Generated by Django 4.2.1 on 2023-07-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbers_cc_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile512',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('src_filename', models.TextField(blank=True, null=True)),
                ('src_pixel_xl', models.BigIntegerField(null=True)),
                ('src_pixel_xr', models.BigIntegerField(null=True)),
                ('src_pixel_yu', models.BigIntegerField(null=True)),
                ('src_pixel_ud', models.BigIntegerField(null=True)),
                ('embedding', models.JSONField(null=True)),
                ('cdf', models.JSONField(null=True)),
                ('metadata', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'cbers_cc_plugin"."tile_512',
            },
        ),
    ]
