# Generated by Django 4.2.1 on 2023-08-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbers_cc_plugin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile512',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
