# Generated by Django 4.2.1 on 2023-05-28 19:03

from django.db import migrations
from django.contrib.auth.models import User
import os
import environ
env = environ.Env()
environ.Env.read_env()


def create_superuser(apps, schema_editor):
    user = User.objects.create_user(
        username=os.getenv('SUPERUSER_USERNAME', default=env('SUPERUSER_USERNAME')),
        password=os.getenv('SUPERUSER_PASSWORD', default=env('SUPERUSER_PASSWORD')),
        is_staff=True,
        is_superuser=True,
    )
    user.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]